### ISSUE TITLE
Samsung Galaxy launches main app instead of 'Key Mapper: side key' for remap of double press

### ISSUE THREAD

**Issue by githubsterer** [keymapperorg/KeyMapper#1535]
**Developer TODO (don't remove)**
- [ ] update documentation

**Describe the bug**
Not sure exactly how this is supposed to work, but every way I can think of still doesn't work. 

True, there is an option to not set the app as an assistant but still not working. Also giving the option for a short press of the side button is a non starter because the system reserves that for turning off the screen. 

I set the built in option to the secondary app (which it surprisingly found listed) but that didn't help. 

If you have specific instructions on this please advise.

**Comment by sds100** [comment]
Please send screenshots of Key Mapper home screen and your side key settings in your phone's settings app.

**Comment by jambl3r** [comment]
I mean in the Key mapper Trigger settings. You have turned on 'double press' inside Key Mapper, but I don't think its necessary.
![Image](https://github.com/user-attachments/assets/70ec84e3-2ac7-45e8-89f4-65bae3945d8b)

**Comment by githubsterer** [comment]
It now looks like this but again, double press does nothing and single press turns off the screen. 

![Image](https://github.com/user-attachments/assets/61e14133-cba9-44d1-9415-295280d5b3df)

**Comment by jambl3r** [comment]
Okay, what options are available in the list of apps when you're setting up the double press action?
Is there only listed 'Key Mapper' or is there also 'Key Mapper: side key'?
![Image](https://github.com/user-attachments/assets/756288e5-9954-45e4-ac3e-36a456005faa)

**Comment by githubsterer** [comment]
Actually there is only the key mapper side key in the list, but when selected it shows the key mapper name in the settings.

**Comment by githubsterer** [comment]
![Image](https://github.com/user-attachments/assets/31141dfc-9788-4e0f-bbdd-6af815943b82)

![Image](https://github.com/user-attachments/assets/5a4f846c-a343-4710-9ceb-7e4e8a951fac)

**Comment by jambl3r** [comment]
> Actually there is only the key mapper side key in the list, but when selected it shows the key mapper name in the settings. 

This is a bit suspicious, but I'm surprised nothing happens at all when you trigger the app. If you choose any other app at all in that menu does the app open when you double press the power button?

**Comment by jambl3r** [comment]
Could you please follow these steps:

1. Make sure Key Mapper: side key is the selected app for double press.
2. Go to Key Mapper Settings
3. Enable extra logging and tap 'View and share log'
4. Tap the 3 dot menu and choose clear
5. Leave the app and try double pressing the power button
6. Send a screenshot of the log

**Comment by githubsterer** [comment]
03/17 09:28:28.022  MainActivity: onResume. Version: 2.8.2
03/17 09:28:28.024  Device assistant activity enabled: true
03/17 09:28:28.029  Accessibility service: checking if it is crashed
03/17 09:28:28.031  Battery optimisation is disabled
03/17 09:28:28.062  Service received event from UI: Ping(key=check_is_crashed)
03/17 09:28:28.066  Received event from service: Pong(key=check_is_crashed)

**Comment by jambl3r** [comment]
Your screenshot looks cut off but I assume there is not more than that?

I'm at a bit of a loss with this. I'll discuss this with the developer later, probably today.
Bit strange that the standard app is not available in that list, and makes me suspicious of what app is even being launched.

**Comment by githubsterer** [comment]
There was another key press to make the screenshot. Here's without that by taking the screenshot manually. 

![Image](https://github.com/user-attachments/assets/7187b67e-44a3-408c-a29a-cf5a6eeaed7f)

**Comment by githubsterer** [comment]
Another reason why you know it's not working is that the way it should be is that launching the secondary app should actually run the assigned key map when pressing the icon from the apps screen actually does nothing. Doing the same with the Tasker secondary app actually performs the linked task, which should be happening here as well.

**Comment by jambl3r** [comment]
I also experience that actually, opening the side key app from the launcher does nothing.

**Comment by sds100** [comment]
I think I know why this is happening. I'm a moron sorry 😅 Gonna close this as fixed.

**Comment by githubsterer** [comment]
That's great news but like the the other fixes it would be nice to get a updated revision sooner than later.

**Comment by githubsterer** [comment]
Would also capitalize Side Key in app name.

**Comment by jambl3r** [comment]
> Would also capitalize Side Key in app name.

done

**Comment by githubsterer** [comment]
Version 2.8.3 from Play Store:

Good news and bad news. 

Good news is that for the first time, pressing the second app from the home screen launches the assigned key map.

Bad news is that although the second app is recognized in the app list to be selected for the side key, as before the name reflected once chosen is just the main app and so the actual side button action still isn't working because all it does it launch the main app. 

So you're half way there!

**Comment by githubsterer** [comment]
To be clear, double pressing the side button does now work for the first time (!) it's just that doing so simply launches the app rather than the key map associated to it. 

Opening the second app from the home screen now also works (!) so the missing link is that Settings does not quite recognize the second app. It does so to the extent that it comes up as a selection in the list, but not enough to actually launch it.

**Comment by jambl3r** [comment]
Hmm, strange. Reopened so we will investigate at some point

**Comment by jambl3r** [comment]
This is a language problem that I will probably make an issue for.

The thing is it's not about how many times you 'press' the button, it's how many times your app of choice (OneUI in this case) tells Key Mapper to do something.

When you double press the side key, OneUI sends 1 request to Key Mapper. So as far as Key Mapper is concerned that is a 'short press'.

For a 'double press', OneUI would need to send 2 requests to Key Mapper, which would require 4 presses of the side key.

The side key / assistant trigger is the only trigger that behaves like this because it is at the mercy of what ever app interprets your key presses before talking to Key Mapper

**Comment by githubsterer** [comment]
Yet definitely needs clarification because the triggers consistently imply how they should be pressed within Key Mapper, so in its plain meaning, the user would rightly expect it to mean pressing the physical button once or twice.

**Comment by sds100** [comment]
Someone else also reported this problem via email today. This should have higher priority. I'll test again on my Samsung Galaxy Tab S5e on Android 11.

**Comment by sds100** [comment]
My Android 11 Samsung doesn't have the issue. @githubsterer can you test this debug apk. You do not need to uninstall your existing Key Mapper. Set the Key Mapper Debug app as the long and double press side key app in Samsung Settings. Then share the log by going to the bottom of the Key Mapper settings page -> "View and share log". I'll need the whole history so click the save button. I need all the text in red.

https://drive.google.com/file/d/1cGJxWRpJUojoZSN0felMrYyie0M8EEAw/view?usp=sharing

**Comment by githubsterer** [comment]
Attaching below. To be clear the long press side button only works with Registar. See these screens. 

![Image](https://github.com/user-attachments/assets/42e72331-cab1-4d99-9e5f-18600eb5188d)
![Image](https://github.com/user-attachments/assets/5ac2b5a5-560f-4413-87e2-9d35fdedee1b)
![Image](https://github.com/user-attachments/assets/f07dc1de-9508-42eb-8faf-0f7cbd4d4e92)
[key_mapper_log_20250413-144538.txt.zip](https://github.com/user-attachments/files/19726739/key_mapper_log_20250413-144538.txt.zip)

**Comment by sds100** [comment]
Oh, I forgot to say actually launch Key Mapper Debug with the double and long press 😂

**Comment by githubsterer** [comment]
Log attached. Create a key map using the side button and then double pressed and long pressed. 

[key_mapper_log_20250413-145635.txt.zip](https://github.com/user-attachments/files/19726767/key_mapper_log_20250413-145635.txt.zip)

**Comment by sds100** [comment]
Can you close the Key Mapper app from the recents/background screen after you launch it. Want to know what happens on a fresh launch. Then send another log. I'm looking for some "onCreate: ...." text in red in the log.

**Comment by githubsterer** [comment]
Ok closed down Key Mapper and pressed the side button from the home screen. 

[key_mapper_log_20250413-150247.txt.zip](https://github.com/user-attachments/files/19726799/key_mapper_log_20250413-150247.txt.zip)

**Comment by sds100** [comment]
It's still not in there 😂 Did you wait 10 seconds for the system to actually clear Key Mapper from the background when you swiped it away?

**Comment by githubsterer** [comment]
Waited a full minute after dismissing the app and then pressed the button from the home screen, launched the app and saved the log. 

[key_mapper_log_20250413-151655.txt.zip](https://github.com/user-attachments/files/19726863/key_mapper_log_20250413-151655.txt.zip)

**Comment by sds100** [comment]
Are you sending the log from the correct Key Mapper app? The debug version should be version 3.0.1 and the log says 3.0.0.

**Comment by githubsterer** [comment]
Sorry, didn't understand that. Here's what you're looking for: 

04/13 14:56:09.694  Battery optimisation is enabled
04/13 14:56:16.518  onCreate = Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200024 cmp=io.github.sds100.keymapper.debug/io.github.sds100.keymapper.MainActivity }
04/13 14:56:16.543  Battery optimisation is enabled
04/13 14:56:16.558  MainActivity: onResume. Version: 3.0.1-debug
04/13 14:56:16.718  Battery optimisation is enabled
04/13 15:02:21.345  Battery optimisation is enabled
04/13 15:02:30.343  Battery optimisation is enabled
04/13 15:16:32.909  Battery optimisation is enabled
04/13 15:34:05.246  Battery optimisation is enabled

**Comment by sds100** [comment]
Thanks. There should be multiple of those onCreate messages from when you open the app manually and launch it from the side key. Can you send them all and see if there is any difference?

**Comment by githubsterer** [comment]
This if everything after opening the app manually, then killing it in the background and then pressing the side button. 

[key_mapper_log_20250413-162407.txt.zip](https://github.com/user-attachments/files/19727110/key_mapper_log_20250413-162407.txt.zip)

**Comment by githubsterer** [comment]
Was that at all helpful?

**Comment by sds100** [comment]
Hmm, nothing in there that really helps us :/

**Comment by sds100** [comment]
@githubsterer Can you try the latest internal testing build. The side key activity has been renamed so it is alphabetically before Key Mapper. I wonder if that solves this problem

**Comment by githubsterer** [comment]
Can you point me to the testing build I need to download please?

**Comment by githubsterer** [comment]
To confirm, 3.0.1.99

**Comment by githubsterer** [comment]
Here are the steps I just too, to confirm this is what you wanted:

1)  I set both the Android system setting Double Press and the Good Lock Registar Long Press to the Key Mapper Debug app.
2) Using the Key Mapper version above, I created a kay map triggered by a Side Key/Power Button Short Press to open the camera.
3) Double pressing the side button opens the Debug App.
4) Long pressing the side button opens the Debug App.

So I guess it's not working. 

Also, as I've said before, there is no Short Press of the side button (at least for Samsung) because that is reserved for turning off the screen, so having that label for the Side Key/Power Button trigger is VERY confusing and needs to be changed to a Long Press.

**Comment by sds100** [comment]
Thats the correct version and it sucks it doesn't fix the problem. Can you try updating in google play again - it should be version 3.0.1 100. Does it work now? I just set the default activity to the assistant trigger so hopefully that works. This also means opening the app from Google Play or the Settings app will launch the assistant trigger too.

**Comment by githubsterer** [comment]
Still does not work. Long press or double press the side key does not perform the action (open camera) but merely opens the secondary app. 

Interestingly, though, when configuring the side button in Settings and Registar it does the Key Mapper Side Key app as selectable and present, when it is not. I only have the Debugger version of the secondary app loaded at this point. For fun, I assigned that Side Key app to those settings and pressing the side button does nothing since it doesn't exist, which makes sense. 

But the bottom line is that so far, no luck on getting this to work.

**Comment by sds100** [comment]
Version 100 still doesn't work? I'd be _very_ surprised by that. The activity should be called "Key Mapper: Side Key". 100% sure you selected that and not some other debug build of Key Mapper?

**Comment by sds100** [comment]
I can't remember, did the Tasker secondary app work?

**Comment by githubsterer** [comment]
Ok, a lot to report: 

1) Since you didn't ever tell me otherwise, I have been testing exclusively the Debugger version of the side app since you sent it to me. So all of these cumulative changes you've made up to this point to get the side button to with may not have been necessary with the standard side app, I just couldn't tell you at this point, but it's definitely worth rolling then back since it sounds like you did some other things in this area that makes launching it more difficult from other screens. 

2) Only yesterday did I realize that for some reason when both side apps are present does the Debugger version take over and the standard version disappears from the home screen but is still showing in the file selector, but that is irrelevant after deleting the Debugger version. 

3)  The good news is that it finally works now, but a few caveats. 

First, and I don't know if this is limited to this one action, but when setting the action to camera, it prompts a dialog to choose which app to use, Camera or Tasker Secondary App. Tasker has nothing to do with this action or anything else related to Key Mapper so I'm not sure why that's happening. Choosing Camera Always gives that, but it shouldn't be showing in the first place.

Second, again, the trigger situation must be addressed because it is very confusing and likely led to earlier false negatives in testing. There can never be a short press trigger with the side key because that turns off the screen always. There is only a long press. The double press works but it's tricky when trying to activate while also avoiding it being received as a single press that turns off the screen. 

Third, the expected behavior isn't quite matching up because it gets complicated when you add Registar into the mix, which allows you to override the regular long press in Settings that only provides two fixed options, Bixby or Power Off screen. 

With Registar turned off completely and the Settings for double press set to the Secondary Side Button App, the key map works whether the trigger is set to short press or double press. In other words, the trigger type is taken over and now

**Comment by githubsterer** [comment]
Ok, a lot to report: 

1) Since you didn't ever tell me otherwise, I have been testing exclusively the Debugger version of the side app since you sent it to me. So all of these cumulative changes you've made up to this point to get the side button to work may not have been necessary with the standard side app, I just couldn't tell you at this point, but it's definitely worth rolling them back since it sounds like you did some other suboptimal things  that makes launching it more difficult from other screens. 

2) Only now did I realize that for some reason when both side apps are present does the Debugger version take over and the standard version disappears from the home screen but is still showing in the file selector, but that is irrelevant after deleting the Debugger version. 

3)  The good news is that the side button key map triggers finally work now, but with a few caveats. 

First, and I don't know if this is limited to this one action, but when setting the action to camera, it prompts a dialog to choose which app to use, Camera or Tasker Secondary App. Tasker has nothing to do with this action or anything else related to Key Mapper so I'm not sure why that's happening. Choosing Camera Always gives that, but it shouldn't be showing in the first place.

Second, again, the trigger situation must be addressed because it is very confusing and likely led to earlier false negatives in testing. There can never be a short press trigger with the side key because that turns off the screen always. There is only a long press. The double press works but it's tricky when trying to activate while also avoiding it being received as a single press that turns off the screen. 

Third, the expected behavior isn't quite matching up because it gets complicated when you add Registar into the mix, which allows you to override the regular long press in Settings that only provides two fixed options, Bixby or Power Off screen. 

With Registar turned off completely and the Settings for double press set to the Secondary Side Button App, the key map works whether the trigger is set to short press or double press. In other words, the trigger type is taken over by Samsung and now controls, which makes it somewhat confusing to have the user choose anything for the trigger. 

However, as an aside, the entire double press side button (even without Key Mapper involved) is awkward because you often don't get the presses right and the screen locks accidentally instead of doing what it's supposed to, and there's no way to turn that off. 

So a huge feature would be having a trigger setting that translates the long press of at least x MS but no longer than y MS into a double press to ensure it gets done right, and anything longer would then be used for the long press. 

Now, once Registar is turned on and overrides the long press of the Settings, when the key map trigger is set to short press everything works as expected but of course with only one side app you don't get separate functionality, which defeats the entire purpose of Registar. So you need at least two side apps, and perhaps more if there's some way to stack triggers with the side key, though I haven't tested that and imagine it to be pretty difficult to accomplish with the short press screen lock issue. 

When the trigger is set to double press, the key map doesn't work at all. If the double press is set to the camera, it will open but if it's set to the side app then nothing happens. 

My takeaway from all this is, you need to remove trigger types to choose from altogether when setting up the side key app and explain in the help that when doing so the trigger is controlled by Settings and Registar. 

And you need to have the ability to set those settings to separate side apps that can activate different actions, otherwise there's little point to the entire feature. Given that a short press is impossible, I don't see any functionality for sequencing the side button with itself, and doing so with the volume keys is already reserved for accessibility shortcuts so there's no point in even having that option presented to the user. 

The best outcome is that you have the ability to remap both built-in side press options by assigning them to two separate side apps, and maybe have some sequencing to get you more options, but that seems doubtful. 

The only additional feature that adds super extra value would be some way to intervene in the double press process because it often doesn't work well due to the screen lock, by allowing the user to substitute a medium long press for a double press and a longer long press for the long press. I would envision that to reside in the Key Mapper settings area.

**Comment by sds100** [comment]
I remember I couldn't find a way to fix this, so i guess samsung users can use expert mode instead
